version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./node_modules:/var/www/html/node_modules
    networks:
      - tasknet
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: task-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - tasknet
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: task-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
      MYSQL_USER: task_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tasknet

networks:
  tasknet:
    driver: bridge

volumes:
  dbdata:
